#!/bin/bash

ARGS=$*
pause=false

clear
while [ true ] ; do
  $ARGS
  res=$?

  echo
  if [ "$res" -eq "0" ]; then
    echo -e '\E[32m'
    echo OK
  else
    echo -en '\E[31m'
    echo "Failed ($res)"
  fi
  echo -en "\033[0m"

  if $pause ; then
    sleep 0.5
  else
    pause=true
  fi
  inotifywait -q *
  clear
done
