#!/bin/bash -e

ARGS=$*
pause=false
platform=`uname`

function wait_darwin() {
  fswatch -r -1 .
}

function wait_linux() {
  inotifywait \
    --recursive \
    --quiet \
    --event modify \
    --event close_write \
    --event move \
    --event create \
    --event delete \
    --exclude \.swp \
    *
}

function await_change() {
  if [ "$platform" == 'Darwin' ]; then
    wait_darwin
  else
    wait_linux
  fi
}

clear
while [ true ] ; do
  set +e
  $ARGS
  res=$?
  set -e

  echo
  if [ "$res" -eq "0" ]; then
    echo -e '\E[32m'
    echo OK
  else
    echo -en '\E[31m'
    echo "Failed ($res)"
  fi
  echo -en "\033[0m"

  if $pause ; then
    sleep 0.5
  else
    pause=true
  fi

  await_change

  clear
done
